name: Deploy to Vercel
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Bitwarden Secrets Manager CLI
        run: |
          # Scarica ed installa l'eseguibile 'bws'
          curl -LO "https://github.com/bitwarden/sdk/releases/download/bws-v0.4.0/bws-x86_64-unknown-linux-gnu-0.4.0.zip"
          unzip bws-x86_64-unknown-linux-gnu-0.4.0.zip
          sudo mv bws /usr/local/bin/

      - name: Fetch All Secrets from Project
        id: secrets_step
        run: |
          SECRETS_JSON=$(bws secret list e2a69413-8a1d-482d-9245-b42c00860ca0)
          VERCEL_ENV_FLAGS=$(echo $SECRETS_JSON | jq -r '.[] | "--env \(.key)=\(.value)"' | tr '\n' ' ')
          echo "VERCEL_FLAGS=$VERCEL_ENV_FLAGS" >> $GITHUB_ENV
        env:
          BWS_ACCESS_TOKEN: ${{ secrets.BWS_ACCESS_TOKEN }}
          BWS_IDENTITY_URL: https://vault.bitwarden.eu/identity
          BWS_API_URL: https://vault.bitwarden.eu/api

      - name: Deploy to Vercel
        run: |
          npm install --global vercel
          # Il comando usa i segreti di GitHub per l'autenticazione 
          # e la variabile di Bitwarden per l'ambiente
          vercel deploy --prod \
            --token=${{ secrets.VERCEL_TOKEN }} \
            --scope ${{ secrets.VERCEL_ORG_ID }} \
            --id ${{ secrets.VERCEL_PROJECT_ID }} \
            ${{ env.VERCEL_ENV_FLAGS }} \
            --yes